import { Card, Badge } from "../ui";
import { HiSparkles as SparkleIcon, HiOutlineTrendingUp, HiOutlineExclamation, HiOutlineInformationCircle } from "react-icons/hi";

export default function AIInsightsPanel({ insights }) {
  if (!insights || insights.length === 0) return null;

  const getIcon = (type) => {
    switch (type) {
      case "opportunity":
        return <HiOutlineTrendingUp className="h-5 w-5 text-emerald-500" />;
      case "warning":
        return <HiOutlineExclamation className="h-5 w-5 text-amber-500" />;
      default:
        return <HiOutlineInformationCircle className="h-5 w-5 text-blue-500" />;
    }
  };

  const getBadgeVariant = (type) => {
    switch (type) {
      case "opportunity":
        return "success";
      case "warning":
        return "warning";
      default:
        return "primary";
    }
  };

  return (
    <Card
      title="AI Intelligence & Recommendations"
      description="Real-time agricultural insights generated by Gemini AI"
      className="p-5"
    >
      <div className="space-y-4 mt-2">
        {insights.map((insight) => (
          <div
            key={insight.id}
            className="flex items-start gap-3 rounded-2xl border border-border/80 bg-muted/20 p-4 transition-all hover:bg-muted/40 hover:border-emerald-500/30"
          >
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-background border border-border shadow-sm">
              {getIcon(insight.type)}
            </div>
            <div className="flex-1 space-y-1">
              <div className="flex items-center justify-between gap-2">
                <p className="font-semibold text-sm">{insight.title}</p>
                <Badge variant={getBadgeVariant(insight.type)}>{insight.tag}</Badge>
              </div>
              <p className="text-xs text-muted-foreground leading-relaxed">
                {insight.description}
              </p>
            </div>
          </div>
        ))}
      </div>
    </Card>
  );
}
